global:
  resolve_timeout: 2m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'test@gmail.com'
        from: 'tes@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'abcd@gmail.com'
        auth_password: ''  # Replace with App Password
        send_resolved: true

inhibit_rules: []